### ISSUE TITLE
Performance of getPropertyDescriptor 

### ISSUE THREAD

**Issue by jascodes** [cronn/reflection-util#10]
Hey @bwaldvogel 

Thanks for great effort and putting it it out there for public use.

Does reflection happen on runtime, which I think generally the case. If so is their way to codegen etc to do this on compile time? If so do you know any other project that already do that? 

Stay Safe
Jas

**Comment by bwaldvogel** [comment]
Yes, reflection happens at runtime but it’s cached. So generally the first invocation is the expensive one. All subsequent invocations should be fast(er).
Please see the [JMH benchmarks](https://github.com/cronn/reflection-util#jmh-benchmark) of this project to get a first impression of the performance impact.

The performance overhead might be not acceptable in your use case.
Compile time code generation approaches indeed exist. One popular example is Hibernate’s [Static Metamodel Generator](https://docs.jboss.org/hibernate/orm/5.0/topical/html/metamodelgen/MetamodelGenerator.html).

**Comment by jascodes** [comment]
@bwaldvogel Thank for you reply; very helpful Information !!!

Thx
Jas

**Comment by jascodes** [comment]
Hey @bwaldvogel 
Static Metamodel Generator only seems to generate for classes annotated as Entities. But I want something for general data class or atleast for class annotated with Document. Any alternative you know of?

Thx
Jas

**Comment by jascodes** [comment]
I actually found lombok has @FieldNameConstants which you can put on class and solve my issue.

Thx
