### ISSUE TITLE
Straight up doesn't work

### ISSUE THREAD

**Issue by Templayer** [cronn/reflection-util#19]
![image](https://user-images.githubusercontent.com/11728067/174249487-4d736d93-d554-484e-9acc-f9ae136ea60b.png)

There is NO documentation, with the exception of:

![image](https://user-images.githubusercontent.com/11728067/174250018-1fadc51d-5167-49cc-9a72-622013bdfa83.png)

**Comment by bwaldvogel** [comment]
I’ve slightly extended the documentation of some `ClassUtils` methods via 7a33df26bbcbe3d2f6348c647dd635ed83615b88.

`ClassUtils.getMethodName(…)` does not support **static** methods.
