### ISSUE TITLE
MethodCaptor cannot capture methods with default visibility

### ISSUE THREAD

**Issue by tobiasgradl** [cronn/reflection-util#9]
When I try to use MethodCaptor for a non-final method with default visibility (i.e., not private), then getCapturedMethod asserts with the message "Method could not be captured. This can happen when no method was invoked or the method is private or final."

Tested with version 2.8.0.

**Comment by bwaldvogel** [comment]
Unfortunately we currently cannot capture methods with default visibility. I’ve improved the exception message in dcfcfa0.

**Comment by bwaldvogel** [comment]
The improved exception message is available with version `2.11.0`.
